### ISSUE TITLE
Feature request: setting for chat history

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#101]
I saw that the chat_history.txt only records the latest answer from the model. Could this be expanded to give the conversation more context with a user setting?

**Comment by BBC-Esq** [comment]
chat_history.txt is only created so that the "Bark" model can read from the .txt file when speaking.  In other words, it doesn't read directly from with box holding the LLM's response, that would be too complex, rather, it reads from the .txt file instead.  It's totally possible to implement some kind of chat history, for a record of your chats, but there still wouldn't be any "memory" as with traditional chat programs (compared to RAG focused programs).  Are you suggesting a "memory" like with chat programs...or just looking to have a history of questions and answers asked in the RAG fashion?

**Comment by clickclack777** [comment]
OK, I see.  I was looking for a memory function that could help expand the context of user questions.

**Comment by BBC-Esq** [comment]
No problem.  I don't have plans to use memory because all RAG applications for my program are in theory single questions as of now...I'm sure it's possible to add history, but I don't see the use case for it...but if someone wants to add it that'd be fine.
