### ISSUE TITLE
feature request: page reference

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#105]
It's great that the referred document is included below the generated text. Would it be possible to include which pages it extracted the text from?

**Comment by BBC-Esq** [comment]
Yes, but only for certain file types like a PDF. Microsoft docx documents, for example, don't have pages per se.  One challenge, however, is going to be as follows: currently the program only displays a source once, even if more than one chunk originate from a specific source, I did this, because if a user a large number of context to be retrieved you don't need to see the same file name if, for example, 100 chunks come from the same file. It would take some serious crafting of code to modify the citation format to list a file name of a source, and then page numbers, for example, file a.PDF pages one through six, 17, pages 23 through 50, etc. you get the point. So while adding page numbers seems simple, it's really not. I originally opted to simply have a file name listed so user could open the file and then search for the particular chunk. They are looking for and then read more surrounding that particular chunk. I hope that makes sense. So I will tentatively approve this one, but it definitely won't be worked on in the near future… Unless I find, a solution that's easier...

**Comment by BBC-Esq** [comment]
One follow-up comment… another scenario is where a chunk begins on one page of a PDF and ends on another page and how do you do that citation. Also, Markovic, cell files, markdown files, and other files don't have pages per se. Even .docx files don't have pages they're XML files basically....txt files don't have pages, etc.

**Comment by clickclack777** [comment]
OK, I understand the challenge. If it only works for pdfs then its more effort than reward. Thanks for the explanation.

**Comment by BBC-Esq** [comment]
It would only be PDFs...so I'll close this out for now...I'll likely incorporate eventually.  Some options like Gpt4All have page numbers, but that platform is extremely slow and only uses one cheap embedding model.  At any rate, mine is the only program that actually shows the chunks...so you can simply search for the chunks if need be...
