### ISSUE TITLE
MacOS installation issue

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#116]
If you're interested in helping giving feedback on installing and running Linux or MacOS drop a line here and/or DM me directly!

**Comment by pl2k2000** [comment]
I just tried since yesterday to install it for M2 Macbook Air with 24GB Ram and it was not a smooth experience at all but managed to make it work at the end. 
Issues:
1. Have to update xcode/tools to the latest
2. Have to manually remove miniconda3 or it will only install old version of PySide6. Not the version 6.6.1 requested.
4. Once above two steps are done, follow the steps from the instruction to install everything
5. You have to install the following missing conpoments too:
pip install ctranslate2
pip install psutil
pip install pynvml
pip install pyaudio
6. Run pip install -r requirements.txt and you will find some version dependency error. in my case, I have to install old version to meet the depemdency:
pip install typing-extensions\>=4.7.1
pip install urllib3==1.26.18

I was able to bring up GUI after all above issues resolved. And the last, when trying to create database from doc files, I got error and have to download to get the resource. 
Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

Others: 
When trying to create vector database, it said the GPU option is available but I could not find a  place to enable it.

**Comment by pl2k2000** [comment]
OK, I have loaded 10 epub books into the database. 

Questions:
1. I added 4 small pdf files and clicked create a database, it looks like wiped out the database (10 books processed) and starting process again with 10 books and 4 pdf. I can't really tell if this is true and can only guess from the process speed. 
2. When query the vector database, is there a way to control the output fields with smae tages? For example, I want to know the answer is from which book and at what page? It seems to give one EXACT paragraph from one book for my question. I am using the bge-large vector model
3. If I want to move the whole plugin setup with vector database to another Maco pc, is there a way/doc on how to do it?

**Comment by pl2k2000** [comment]
After finishing loading 4 short PDFs into the vector database. I submitted a prompt asking one question based on the PDF doc contents but got no answer: The provided context does not contain any information related to (my question). Therefore, it is impossible to provide a relevant answer based on the given context.

**Comment by BBC-Esq** [comment]
Thanks for the information.  I'll do my best to modify the installation process for macos but I can't guarantee results since I don't own or use a mac.  With that being said, miniconda should not be used to install things.  If you're not using it but it's still on your system, I'm not sure why it'd interfere...

If you install via pip, it's been my experience that there shouldn't be any version errors.  Pip determines and resolves them.

Your statement that ctranslate2, psutil, etc. are not installed and that you have to install them separately tells me that something is wrong.  ctranslate2 is explicitly listed within ```requirements.txt``, it's not merely a dependency of another dependency listed in ```requirements.txt```, for example, which might explain why it wasn't installed correctly.  That implies that something on your system is not following the normal operation of pip...I have no way of knowing why that is...miniconda perhaps?

Same concern regarding nltk...but in that case it's a dependency of a dependency.  I have no problem with nltk being installed on my system when I install the requirements.txt...

Regarding using the program, yes, when you add documents and click "create database" it deletes the old one before re-creating it.  There's an "issue" to allow users to create more than one database.

Regarding citations, see the other issues regarding providing page citations and the challenge/priority regarding that.

Regarding moving the plugin...what you describe is just installing it on another computer?

Regarding the 4 pdfs...without a printout of any errors in the command prompt, if you asked a relevant question that you know that the answer is contained within the pdf files, my guess is that you set the "similarity" setting too high.

**Comment by pl2k2000** [comment]
1. On my Macos, PySide6 is installed under miniconda3 subdirectory and that why the miniconda3 gets into the picture
2. There is no version error when doing each pip install. The error comes up when try to verify using pip install -r requirements.txt, the exact error message is coped here: "ERROR: Ignored the following versions that require a different python version: 6.0.0 Requires-Python >=3.6, <3.10; 6.0.1 Requires-Python >=3.6, <3.10; 6.0.2 Requires-Python >=3.6, <3.10; 6.0.3 Requires-Python >=3.6, <3.10; 6.0.4 Requires-Python >=3.6, <3.10; 6.1.0 Requires-Python >=3.6, <3.10; 6.1.1 Requires-Python >=3.6, <3.10; 6.1.2 Requires-Python >=3.6, <3.10; 6.1.3 Requires-Python >=3.6, <3.10; 6.2.0 Requires-Python >=3.6, <3.11; 6.2.1 Requires-Python >=3.6, <3.11; 6.2.2 Requires-Python >=3.6, <3.11; 6.2.2.1 Requires-Python >=3.6, <3.11; 6.2.3 Requires-Python >=3.6, <3.11; 6.2.4 Requires-Python >=3.6, <3.11; 6.3.0 Requires-Python <3.11,>=3.6; 6.3.1 Requires-Python <3.11,>=3.6; 6.3.2 Requires-Python <3.11,>=3.6; 6.4.0 Requires-Python <3.11,>=3.6
ERROR: Could not find a version that satisfies the requirement PySide6==6.6.1 (from versions: 6.4.0.1, 6.4.1, 6.4.2, 6.4.3, 6.5.0, 6.5.1, 6.5.1.1, 6.5.2)
ERROR: No matching distribution found for PySide6==6.6.1"
3. regarding the "similarity" setting, I used the system default. I will try to change it and give another run when I have got some time.
4.moving the plugin -- I am more interesrted in move the database/setting/model/etc, not the plugin code itself which I can do another install
5. delete/recreate database each time when adding a new doc is a deal break for me. The use case is you would like to maitin a local docs on each fields you are interested. It could be 1 or could be 10 subjects, each in a seperate document directory on your disk. You would add doc to the subject directoiry daily (pdf, small article txt, web url, etc). I think you should not delete the existing database, instead you should mark the docs that are already indexed so you do not want to do it again when adding the new doc to the database. You can have a switch set to allow to re-index everything for a new database. 
6. please add a timestamps into log to terminal window so I can tell how long it takes to index 10 books. Feels like a long time > 30 minutes. If I have to index/reindex 100 books/article/pdf each day the application will be useless.
7. I followed each step in the instruction, and completed the pip install -r requirements.txt before call the gui.py, that is the time the missing module message showed up:
line 15, in <module>
    from initialize import main as initialize_system
  File "ChromaDB_LM_Studio/src/initialize.py", line 4, in <module>
    import ctranslate2
ModuleNotFoundError: No module named 'ctranslate2'

**Comment by pl2k2000** [comment]
Let me share the error message when trying to run requirements.txt firsttime after complete the installation steps (I have to downgrade the version on my system to pass the check): 

pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-macos 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.9.0 which is incompatible.
google-auth 2.22.0 requires urllib3<2.0, but you have urllib3 2.2.0 which is incompatible.

**Comment by BBC-Esq** [comment]
Are you creating a virtual environment like my installation instructions say?  I'm not sure why tensorflow would be installed if so...

If it works when you pip install everything individually, I'm not sure I can help you troubleshoot without knowing a slew more information about your system..

**Comment by pl2k2000** [comment]
Some feedback on the first test of the plugin usage.
Setup:
LM Studio loaded with model mythomax-l2-13b.Q5_K_M.gguf
the "similarity" setting is 0
I am using the bge-large vector model
10 ebook on the topic of Home Remedies were indexed

1. after all ebooks were indexed, I quiried one question from one ebook and got an answer and the answer text was from the ebook as expected. This is the good part.

Next I added 4 PDF files into the plugin, and the plugin deleted ALL old index nd re-indexed 10 ebook and 4 PDF filesd. The PDF files are small articles on how to step by step fine turning a LLM model on the Mac. After the finish, **I have to restart the plugin** otherwise when I ask LLM question, LM Studio just returned "The provided context does not contain any information related to (my question). Therefore, it is impossible to provide a relevant answer based on the given context."

2. In PDF articles, there is a sub title like "Step 2: Pull the model from Hugging Face and convert to an MLX
compatible model", it talks about how to check MLX compatible format and how to convert using python convert.py script.
When I query the vector database on the EXACPT question for the article sub title, it DOES NOT return the article content at all. It just retuned knowledge from the LLM model alone, like check the bard or Model card etc. This is not I have expected and I do not know what I am doing wrong.

3. On above step2, the return result also wrongly added the some ebook file names at the end (always), plus some PDF file names (some times). The ebook has nothing to do with my LLM quetion. Does this mean the PDF index is not doing correectly? How do you check?

**Comment by pl2k2000** [comment]
I did creating a virtual environmentper per your installation instructions.

**Comment by pl2k2000** [comment]
All are just my feedback on my Macos installation. I managed to complete the install at end and it works fine right now. I am testing the plugin features.

**Comment by BBC-Esq** [comment]
OK, if you have time please send me a list of the steps that worked for you..that way I can try to revise installation for macos without having it.  lol

**Comment by pl2k2000** [comment]
My successful steps were outlined in my first comment above.

**Comment by BBC-Esq** [comment]
OK, thought you did a different approach.  closing as resolved.
