### ISSUE TITLE
Font Error

### ISSUE THREAD

**Issue by mmuyakwa** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#15]
Hi,

Stumbled upon this project.
Installed it and ran the GUI.

I cannot see _(read)_ anything.

When running:
**"python gui.py"**

I get the info-message:
**"qt.qpa.fonts: Populating font family aliases took 207 ms. Replace uses of missing font family "Segoe UI Historic" with one that exists to avoid this cost."**

![Bildschirmfoto 2023-10-22 um 16 07 50](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/34812005/cfb519a4-02b8-4c58-9b8b-b6d71b9e82d7)

![Bildschirmfoto 2023-10-22 um 16 15 31](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/34812005/39037361-a674-4bb1-96f5-2d6fc945f9bf)

**Comment by BBC-Esq** [comment]
Try modifying this portion of config.yaml to the name of a different font that you know you have installed, save, then restart the program:

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/3f00da6c-05e2-411c-9b99-7c297b2a4f79)

If you'll tell me the font name that you use I can hardcode it as an alternative in case people don't have the Segoe font.  It'd save time after hearing what font worked for you since I don't have a mac.

**Comment by mmuyakwa** [comment]
I went with "Arial Unicode MS".

Looks good now.

![Bildschirmfoto 2023-10-22 um 19 43 38 2](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/34812005/cc3df602-cb65-468c-8f60-054c55dbd42d)

![Bildschirmfoto 2023-10-22 um 19 45 30](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/34812005/16371bd9-37c9-4145-9365-7735eae9ea04)

**Comment by BBC-Esq** [comment]
Renamed and pinned the issues for others to see just in case.  Easier than revising the scripts to provide for fallback fonts.
