### ISSUE TITLE
Feature Request for ingesting web sites

### ISSUE THREAD

**Issue by zarlor** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#28]
In addition to being able to upload files would it also be possible to provide a URL to have this ingest a web page or even that page and its sub-pages into the database? In particular it may be helpful for Wiki style pages to be pulled for specific use cases where being able to reference a particular subject matter or sets of subject would be helpful.

**Comment by BBC-Esq** [comment]
My concern is that various websites have widely different structures, so it would be hard to basically create one ingest script for all websites.  I might implement something in the future for specific websites, like downloading and putting into the database all scripts from a GitHub repository...Kind of different though.  Plus, trying to keep my program as non-internet/local as possible since most services like Chat GPT are cloud based.
