### ISSUE TITLE
AMD gpu support for windows

### ISSUE THREAD

**Issue by pspsdev** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#4]
I'm wondering if AMD gpu support for windows is in the pipeline?

I have 7900 XTX and could test whatever changes is needed.

**Comment by BBC-Esq** [comment]
I would, but PyTorch, upon which this program relies, does not currently support AMD GPU acceleration on Windows - only Linux.  However, there are some projects that take a stab at it and I'm not sure if they've succeeded yet.  It appears they have, but for me personally it'd involve learning a lot of new things...alas, time constraints.

I estimate it'd take me 10 hours of programming to add AMD GPU support for Windows, with someone by my side willing to test every step of the way since I don't have an AMD GPU...Are you willing to put in that kind of time along with me?  ;-)

Here's some of the links I've come across:

[https://github.com/llvm/torch-mlir](url)
[https://pypi.org/project/torch-directml/](url)
[https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows](url)
[https://github.com/microsoft/directml#pytorch-with-directml](url)

**Comment by BBC-Esq** [comment]
You mentioned being willing to test.  Please see my revised instructions on the readme to see how it might be possible to get it working using Windows Subsystem for Linux.  There are two links there that might immediately make it workable!  Please let me know.

**Comment by BBC-Esq** [comment]
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/b34a5dce-5220-4af8-b740-3b1a8330bbe4)

**Comment by BBC-Esq** [comment]
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/e2d6e097-38c5-4e38-9a1f-f28441ba8812)

**Comment by BBC-Esq** [comment]
Lack of interest and I don't have an AMD gpu so can't test.
