### ISSUE TITLE
Add citations to results obtained either when getting a response from the LLM and/or "test embeddings" is checked.

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#44]
It's useful to have citations.  Better yet, citations that are hyperlinked to the files on your computer.

This could be displayed near where the LLM's response is received in a separate widget or in a scrollable widget nearby...It could also be displayed in a popup if/when a user clicks a button to display "sources" or "citations," for example.

The sources/citations must not be expected from the LLM is my thought.  E.g., don't tell the LLM to provide the sources/citations, because it's not required to.  Rather, gather the citations from the contexts provided to the LLM before the "contexts" are sent to the LLM.  When a response is received, populate the citations to the appropriate widget near the LLM's response...thus, not relying on the LLM to quote the sources in its response.

Key challenge: how to handle situations where an LLM provides a response that, for example, relies on 3 out of 15 contexts provided to it.  Do we really need 15 citations displayed...is there some way to detect the sources that the LLM relies on

Having all 15 is better than no sources whatsoever, as it is not, so even this is a good starting point.

HYPERLINK the sources to the file paths so a user can click on the relevant file and open it with a default program on their computer.

Getting sources requires inputting "metadata" into chromadb at the time the DB is created, which is significant.  It requires obtaining the metadata.  For starters, let's at least get the file name and path to the file...we can worry about other possible metadata later (e.g. page of a PDF or column/row of a spreadsheet).

**Comment by TheRealBeef** [comment]
Perhaps this
1. User submits query, and this query is put into ChromaDB to get the most likely (e.g.) 15 contexts
2. These contexts are sent to the LLM
3. The response is given back from the LLM
4. The response from the LLM is *also* put into ChromaDB to get the the most similar context - could be made more accurate if a new "temp" DB is created only from those 15 contexts ... or even simply vectorize the contexts using SKLearn or similar, since it doesn't have to be as accurate as the ChromaDB. Example from my text classifier here (https://github.com/TheRealBeef/Python_Text_Classifier/blob/82c4f46592ee03af776c593a8c4e202896cfa499/ext_functions.py#L123C44-L123C44)
5. Of those contexts sent to the LLM the one (or two) that most closely matches the response is the one that has the citation provided

**Comment by BBC-Esq** [comment]
Last night I found the structure of how to put metadata into the vector database...turns out that my loaders were already doing it automatically, at least for pdfs.  I still need to check all the other loaders as well though.  If that's the case, I simply need to add a feature to return the metadata (e.g. file path, name, etc.) with what's returned from the vector database.  Right now it's only returning the text...Late last night was, shall we say...educational...

**Comment by BBC-Esq** [comment]
Completed as version 2.7.2 (BUT MAKE SURE TO use the ```server_connector.py``` script attached to that release to replace the official ```server_connector.py``` script that comes in the official release.
