### ISSUE TITLE
Feature requests: Server port, DB folder, LLM request

### ISSUE THREAD

**Issue by cspenn** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#6]
Love the work done so far, and it's great that it's working! 3 requests:

Can we have an option to change the port for LM Studio that is not hardcoded? I typically run LM Studio on port 9001 and while I can modify server_connector.py, it'd be nice to do that in the GUI instead.
It looks like in the GUI when I select docs, they get moved to a Docs_for_DB folder - can we just directly load files into that folder in the OS? (And can we specify a symbolic link to an existing directory folder so we don't have to have duplicates of potentially thousands of documents?)
How do we set things like temperature and max_tokens in the requests to LM Studio?

**Comment by BBC-Esq** [comment]
These things will be worked on!

**Comment by BBC-Esq** [comment]
v2.2.3 released:

The server settings have been added to the GUI in the Settings tab.  Also, added symbolic links instead of files being copied to the database document directory.  Lastly, nothing in the scripts should prevent a user from copying files directly to the database folder and the vector database should be created nonetheless if there are symbolic links as well as actual files, which addresses the remaining feature request.  Good idea.  Feel free to make more suggestions.
