### ISSUE TITLE
How to set the `content` value for ` "role": "system" ` ?

### ISSUE THREAD

**Issue by ThinksFast** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#77]
Hi, thanks so much for making this package, it is awesome!  I want to fine-tune the system role of the LLM with better instructions for the response.

For example, LM Studio provides this example `curl` code, which includes instructions to have the response rhyme:  `{ "role": "system", "content": "Always answer in rhymes." }`

What would be the best way to achieve that with the ChromaDB plugin?

```
# Load a model, start the server, and run this example in your terminal
# Choose between streaming and non-streaming mode by setting the "stream" field

curl http://localhost:1234/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{ 
  "messages": [ 
    { "role": "system", "content": "Always answer in rhymes." },
    { "role": "user", "content": "Introduce yourself." }
  ], 
  "temperature": 0.7, 
  "max_tokens": -1,
  "stream": false
}'
```

**Comment by BBC-Esq** [comment]
Hmm...It's been awhile since I've looked at the openai API, but that's where you'd set it I imagine.  Curl does the same thing but I think it might be easier to use the open ai api...

**Comment by ThinksFast** [comment]
Correct, if I was writing Python code, it's a message I would include with the construction of an OpenAI client. But i don't know how I would include this message/content from the GUI that you built.

**Comment by BBC-Esq** [comment]
Well...I thought about it, but what would be the purpose of having it rhyme in is response?  Or was that just one example?  I am trying to keep my program narrowly tailored to vector database related stuff.  If a user wants to just chat with the LLM they should just use LM Studio or another program.  Unless you can point out another use...

**Comment by ThinksFast** [comment]
If I understand it correctly, the `content` a user provides to the system role is like a pre-prompt that gives instructions on how the LLM should respond to all future prompts. The example above is just a copy/paste from LM Studio, but it does show how to make every LLM response in a chat return text that rhymes.  

My goals are a bit different.  I want to instruct the LLM to have a creative writing personality. I'm currently getting somewhat bland output, which I think reads like "AI content". I believe tuning the LLM with this message/content could help achieve the desired content quality, while also using the vector database to expand the LLM's "knowledge".

**Comment by BBC-Esq** [comment]
I'm still having difficulty seeing how that relates to getting clearcut answers regarding documents put into a vector database...I totally get what you're saying, but it's almost counterproductive to get too creative responses when asking, which is why I put the temperature to .1 (0 being no creativity whatsoever).  You can adjust the temperature, did you try that?  Also, I've noticed that different models answer more eloquently than others.  Which model are you using?

**Comment by ThinksFast** [comment]
My use case is a bit different.  I'm trying to use the vector DB to create a knowledge base around particular topics, so I can produce high-quality and factually accurate long-form content for webpages. That's why I want to try giving the LLM a writing personality with the `role:system` content. The tone/voice needs tuning. 

For models, I'm currently playing around with llama2 and orcamaid (32k tokens). I haven't played with the temperature, maybe that'll help

**Comment by BBC-Esq** [comment]
Let me know if it works out.  And remember the other settings within LM Studio still take effect as well, just not the prefix/suffix if you specify my program to use it's own prefix/suffix.  But otherwise, the other settings within LM Studio should take effect.  Another option is to use the vector database to retrieve the necessary chunks only...by selecting the "chunks only" checkbox.  Then simply copy and paste the contexts and your question into LM Studio the normal way.
